### ISSUE TITLE
(Protocol.UndefinedError) protocol Enumerable not implemented for nil

### ISSUE THREAD

**Issue by cdale77** [knrz/haikunator#4]
When I tried `build`, I got the error in the title. It's coming from here:
https://github.com/knrz/haikunator/blob/master/lib/haikunator.ex#L44

I also got deprecation warnings about `random`, it says to use `rand` instead. 

Elixir 1.3.2

**Comment by CyrusNuevoDia** [comment]
Hey, I just pushed version `1.1.0`. It should fix this.

**Comment by cdale77** [comment]
@knrz thanks!
